Button custom width
amwal-tech/amwal-magento pull request #131
Opened 2023-09-21 07:30 UTC by ahmardi

2023-09-21 10:37 UTC, Skullsneeze requested changes

2023-09-21 10:37 UTC, Skullsneeze commented on view/frontend/templates/express/checkout-button.phtml
> +         <?= $triggerContext == 'product-detail-page' ? 'style="width: 49%"' : '' ?>
I wouldn't apply this as inline styling because it's harder to overwrite when needed. I would instead use a class and some css/less

2023-09-25 10:27 UTC, sameh-amwal approved these changes

2023-09-25 10:31 UTC, Skullsneeze requested changes

2023-09-25 10:31 UTC, Skullsneeze commented on view/frontend/templates/express/checkout-button.phtml
> +    <?= $viewModel->getStyleCss() ?>
Let's add escaping for security 
```suggestion
    <?= $escaper->escapeCss($viewModel->getStyleCss()) ?>
```

2023-09-25 10:36 UTC, merged