The first scanned files
amwal-tech/amwal-magento pull request #155
Opened 2023-10-08 12:23 UTC by ahmardi

2023-10-09 08:27 UTC, sameh-amwal approved these changes

2023-10-10 19:17 UTC, Skullsneeze requested changes

2023-10-10 19:17 UTC, Skullsneeze commented on Block/Widget/ExpressCheckoutButton.php
> +        parent::__construct($context, $postDataHelper, $layerResolver, $categoryRepository, $urlHelper, $data);
We should make sure that setTemplate is not called in the parent constructor, else our call is immediately overwritten

2023-10-10 19:17 UTC, Skullsneeze commented on Model/Button/GetConfig.php
>  class GetConfig
I believe we should have a single newline before the class definition

2023-10-10 19:17 UTC, Skullsneeze commented on Model/Checkout/GetQuote.php
> +        $customerAddress = '';
There is no need to pre-define this since an exception is thrown in case the address resolution fails

2023-10-10 19:17 UTC, Skullsneeze commented on Model/Checkout/PlaceOrder.php
> +            	$this->updateCustomerAddress($quote, $customerAddress);
Indenting looks off here

2023-10-10 19:17 UTC, Skullsneeze commented on Model/Data/AmwalOrderDetails.php
> +     * @return \Magento\Sales\Api\Data\OrderInterface
FQN can be imported

2023-10-10 19:17 UTC, Skullsneeze commented on Model/Data/AmwalOrderDetails.php
> +     * @param $order
I think we can add OrderInterface as a typehint here and in the function parameter

2023-12-11 08:42 UTC, closed without merging