Add order dataValidation
amwal-tech/amwal-magento pull request #221
Opened 2023-11-23 09:18 UTC by ahmardi

Exception
![image](https://github.com/amwal-tech/amwal-magento/assets/141551822/8fee316b-6d34-4053-bc21-f27b00801339)

2023-11-23 11:12 UTC, Skullsneeze requested changes

2023-11-23 11:12 UTC, Skullsneeze commented on Model/Data/OrderUpdate.php
> +     * @param Order $order
You're missing the param for amwal order data

2023-11-23 11:12 UTC, Skullsneeze commented on Model/Data/OrderUpdate.php
> +                $orderValue = call_user_func([$order, 'get' . $orderMethod]);
I think both order and amwal order data are data objects, so we should be able to doo something like
```suggestion
                $orderValue = $order->getData($orderField);
```

Where $orderField would be the snake_case version of the fieldd

2023-11-23 11:12 UTC, Skullsneeze commented on Model/Data/OrderUpdate.php
> +        $fields = ['AmwalOrderId' => 'getId', 'RefId' => 'getRefId', 'BaseGrandTotal' => 'getAmount'];
Might be a good idea to as this as a constant instead?

2023-11-23 11:55 UTC, ahmardi commented
![Screenshot 2023-11-23 at 13 54 43](https://github.com/amwal-tech/amwal-magento/assets/141551822/b11309aa-be5b-42c1-92fc-764093aec989)

2023-11-23 11:59 UTC, sameh-amwal approved these changes

2023-11-23 12:15 UTC, Skullsneeze approved these changes

2023-11-23 12:15 UTC, Skullsneeze commented on Model/Data/OrderUpdate.php
> +            foreach ($fields as $orderMethod => $amwalMethod) {
You could use the constant het directly instead of singing it to its own variable first

2023-11-26 10:37 UTC, Skullsneeze approved these changes

2023-11-26 10:38 UTC, merged