return exception and report to sentry
amwal-tech/amwal-magento pull request #241
Opened 2023-12-08 11:25 UTC by ahmardi

2023-12-08 11:26 UTC, Skullsneeze approved these changes

2023-12-08 13:02 UTC, sameh-amwal reviewed
please add throw exception also in dataValidation or remove the try exception block

2023-12-10 08:48 UTC, sameh-amwal commented on Model/Data/OrderUpdate.php
> +            throw new \Exception($e->getMessage());
```suggestion
            throw $e;
```

2023-12-10 09:15 UTC, sameh-amwal approved these changes

2023-12-11 06:21 UTC, Skullsneeze requested changes

2023-12-11 06:21 UTC, Skullsneeze commented on Model/Checkout/PayOrder.php
> +        sentryExceptionReport $sentryExceptionReport
```suggestion
        SentryExceptionReport $sentryExceptionReport
```

2023-12-11 06:21 UTC, Skullsneeze commented on Model/Settings.php
> +            'is_merchant_valida' => $this->config->isMerchantValid(),
```suggestion
            'is_merchant_valid' => $this->config->isMerchantValid(),
```

2023-12-11 07:48 UTC, Skullsneeze approved these changes

2023-12-11 07:49 UTC, Skullsneeze approved these changes

2023-12-17 07:51 UTC, sameh-amwal commented on Model/Data/OrderUpdate.php
> +        if ($order->getOrderCurrencyCode() != $amwalOrderData->getMerchantCountryCode()) {
wouldn't be this comparing currency code (SAR) to country code (SA)?

2023-12-18 10:47 UTC, merged