Add php unit
amwal-tech/amwal-magento pull request #242
Opened 2023-12-12 08:11 UTC by ahmardi

2023-12-12 10:21 UTC, Skullsneeze approved these changes

2023-12-13 23:29 UTC, Skullsneeze requested changes

2023-12-13 23:29 UTC, Skullsneeze commented on Model/Checkout/GetQuote.php
> +        $this->SentryExceptionReport = $sentryExceptionReport;
```suggestion
        $this->sentryExceptionReport = $sentryExceptionReport;
```

2023-12-13 23:29 UTC, Skullsneeze commented on Model/Checkout/GetQuote.php
> +            $this->SentryExceptionReport->report($originalException);
```suggestion
            $this->sentryExceptionReport->report($originalException);
```

2023-12-14 06:07 UTC, Skullsneeze approved these changes

2023-12-14 06:41 UTC, sameh-amwal approved these changes

2023-12-18 08:02 UTC, sameh-amwal approved these changes

2023-12-18 08:02 UTC, merged