Add order-details by orderId end-point
amwal-tech/amwal-magento pull request #243
Opened 2023-12-12 11:43 UTC by ahmardi

2023-12-13 07:37 UTC, Skullsneeze requested changes

2023-12-13 07:37 UTC, Skullsneeze commented on Model/Data/AmwalOrderDetails.php
> +    private function getOrderById($orderId)
```suggestion
    private function getOrderById(string $orderId)
```

2023-12-13 07:37 UTC, Skullsneeze commented on Model/Data/AmwalOrderDetails.php
> +            'order' => $order->getData(),
If you expect a "flat" array without objects I think you can also use `toArray` here (but do first verify if this works for your use case)
```suggestion
            'order' => $order->toArray(),
```

2023-12-13 07:50 UTC, ahmardi commented
@Skullsneeze pls check the phpstan logs in AddressResolverTest https://github.com/amwal-tech/amwal-magento/actions/runs/7192153960/job/19588047503?pr=243

2023-12-18 09:21 UTC, sameh-amwal approved these changes

2023-12-18 10:44 UTC, merged