Add discount ribbon
amwal-tech/amwal-magento pull request #267
Opened 2024-01-29 06:54 UTC by ahmardi

2024-01-30 07:28 UTC, sameh-amwal commented on view/frontend/web/js/amwal-magento-react-button/src/AmwalMagentoReactButton.tsx
> +        // installmentOptionsUrl={config.installment_options_url}
```suggestion
        installmentOptionsUrl={config.installment_options_url}
```

2024-01-30 07:30 UTC, sameh-amwal commented on view/frontend/templates/express/checkout-button.phtml
> +         data-product-id="<?= $escaper->escapeHtmlAttr($viewModel->getProductId()) ?>"
use `$block->getProduct()` to get the product id instead

2024-01-30 15:41 UTC, sameh-amwal approved these changes

2024-02-01 12:19 UTC, Skullsneeze requested changes
Almost there I think :)

2024-02-01 12:19 UTC, Skullsneeze commented on Api/Data/AmwalButtonConfigInterface.php
> +
```suggestion
```

2024-02-01 12:19 UTC, Skullsneeze commented on Model/Button/GetCartButtonConfig.php
> +        if ($triggerContext === 'regular-checkout') {
Let's maybe introduce a constant here for maintainability (defined together with the other constants for trigger context):
```suggestion
        if ($triggerContext ===  ExpressCheckoutButton::TRIGGER_CONTEXT_REGULAR_CHECKOUT) {
```

2024-02-01 12:19 UTC, Skullsneeze commented on Model/Button/GetCartButtonConfig.php
> +            }else {
```suggestion
            } else {
```

2024-02-01 12:19 UTC, Skullsneeze commented on Model/Button/GetCartButtonConfig.php
> +            }else {
```suggestion
            } else {
```

2024-02-01 15:28 UTC, merged