Card bin check refactor
amwal-tech/amwal-magento pull request #360
Opened 2024-07-01 06:55 UTC by ahmardi

2024-07-01 08:41 UTC, sameh-amwal approved these changes

2024-07-01 09:44 UTC, Skullsneeze requested changes

2024-07-01 09:44 UTC, Skullsneeze commented on Model/Checkout/PlaceOrder.php
> +            if ( str_starts_with($card_bin, $bin) ) {
For backwards compatability with PHP versions older than 8
```suggestion
            if (strpos($cardBin, $bin) === 0 ) {
```

2024-07-01 09:44 UTC, Skullsneeze commented on Model/Checkout/PlaceOrder.php
> +        foreach ($cards_bin_codes as $bin) {
Lets follow the naming convention for vars here (camelCase) 
```suggestion
        $cardsBinCodes = $this->config->getCardsBinCodes();
        foreach ($cardsBinCodes as $bin) {
```

2024-07-01 09:44 UTC, Skullsneeze commented on Model/Checkout/PlaceOrder.php
>      private function applyBinDiscountRule(CartInterface $quote, string $card_bin): void
```suggestion
     * @param string $cardBin
     * @return void
     */
    private function applyBinDiscountRule(CartInterface $quote, string $cardBin): void
```

2024-07-03 08:08 UTC, sameh-amwal approved these changes

2024-07-03 08:11 UTC, merged